version: "3"

vars:
  host: "vm"
  arch: "linux"
  disks: 3

tasks:
  homelab-vm:
    cmds:
      - nix run .#nixosConfigurations.homelab.config.system.build.vmWithDisko
      # - |
      #   while true; do
      #     kitty +kitten ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=no -p 2222 kwkaiser@localhost echo 'connected' && break
      #     echo "Connection refused, retrying in 5 seconds..."
      #     sleep 5
      #   done

  clean:
    cmds:
      - rm -rf data
      - rm -rf result
      - rm -rf result-*
      - rm -rf keys
      - rm -rf *.fd
      - rm -rf *.qcow2
