version: "3"

vars:
  host: "vm"
  arch: "linux"
  disks: 3

tasks:
  homelab-vm:
    cmds:
      - nix run .#nixosConfigurations.homelab.config.system.build.vmWithDisko

  clean:
    cmds:
      - rm -rf data
      - rm -rf result
      - rm -rf result-*
      - rm -rf keys
      - rm -rf *.fd
      - rm -rf *.qcow2
