version: "3"

vars:
  host: "vm"
  arch: "linux"
  disks: 3

tasks:
  homelab-vm:
    cmds:
      - QEMU_NET_OPTS="hostfwd=tcp::2222-:22" nix run .#nixosConfigurations.homelab.config.system.build.vmWithDisko > /dev/null 2>&1 &
      - |
        while true; do
          ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=no -p 2222 kwkaiser@localhost && break
          echo "Connection refused, retrying in 5 seconds..."
          sleep 5
        done

  clean:
    cmds:
      - rm -rf data
      - rm -rf result
      - rm -rf result-*
      - rm -rf keys
      - rm -rf *.fd
      - rm -rf *.qcow2
