version: "3"

vars:
  host: "vm"
  arch: "linux"
  disks: 3

tasks:
  homelab-vm:
    cmds:
      - |
        export XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-/run/user/$(id -u)}
        export WAYLAND_DISPLAY=${WAYLAND_DISPLAY:-wayland-1}
        export DISPLAY=${DISPLAY:-:0}
        sudo -E nix run .#nixosConfigurations.homelab.config.system.build.vm & # need sudo for port forwards

      - |
        while true; do
          ssh homelab-vm echo 'connected' && break
          sleep 5
        done
      - sleep 10
      - ssh homelab-vm sudo cat /etc/rancher/k3s/k3s.yaml > ~/.kube/config

  homelab-ports:
    desc: Forward privileged ports (80/443) to VM services via SSH tunnel
    cmds:
      - |
        echo "Waiting for VM SSH to be ready..."
        while true; do
          ssh homelab-vm echo 'connected' 2>/dev/null && break
          sleep 2
        done
      - |
        echo "Forwarding localhost:443 → VM:30443 and localhost:80 → VM:30080"
        echo "Press Ctrl+C to stop"
        sudo ssh -L 443:localhost:30443 -L 80:localhost:30080 -N homelab-vm

  clean:
    cmds:
      - rm -rf data
      - rm -rf result
      - rm -rf result-*
      - rm -rf keys
      - rm -rf *.fd
      - rm -rf *.qcow2
