[project]
name     = "homelab-vps"
revision = "1.0"

[profiles.default]
TF_VAR_linode_token = { required = true, description = "Linode API token (terraform provider auth)", providers = [
  "kdbx",
], ref = { item = "personal/projects/homelab/linode access token", field = "Password" } }
